### ISSUE TITLE
Функционал сайта

### ISSUE THREAD

**Issue by vendmm** [CosmoBoyMe/Toxin#10]
При запуске дев сервера на сайте ломаются все картинки

![2022-09-23-11-16-19](https://user-images.githubusercontent.com/90188872/191949348-b700466b-2468-46f6-86fb-724c0f880e1e.png)
![2022-09-23-11-00-29](https://user-images.githubusercontent.com/90188872/191949377-091a2f1f-d9fa-4d44-bbd2-4bafba7b49cd.png)

**Comment by vendmm** [comment]
Лого в футере лучше сделать ссылкой, аналогично тому, что в хедере

**Comment by vendmm** [comment]
Есть некоторые проблемы с бордером дропдауна, когда он закрыт
![2022-09-23-11-06-06](https://user-images.githubusercontent.com/90188872/191949824-58d47aca-bb97-4203-80e6-2d30ef7ff205.png)


Когда дропдаун открыт, бордер инпута с фразой "Сколько гостей" должен быть того же цвета, что и нижняя часть компонента
![2022-09-23-11-26-36](https://user-images.githubusercontent.com/90188872/191950050-6f4c983e-66d9-4e31-941f-0e48f46b461e.png)


Знаки "+" и "-" выглядят странно, лучше заменить их обычными + и -
![2022-09-23-11-25-28](https://user-images.githubusercontent.com/90188872/191950308-01104918-1c12-4141-a712-792cac3a4e66.png)

**Comment by vendmm** [comment]
![2022-09-23-11-08-03](https://user-images.githubusercontent.com/90188872/191950371-510a10ca-c5d3-4666-a35d-3dd92999b033.png)

**Comment by vendmm** [comment]
Внешний вид карточки с комнатами не соотв. макетам
(макет)
![2022-09-23-11-14-51](https://user-images.githubusercontent.com/90188872/191950496-fd070e03-eb4e-415b-ac85-aae14da4069e.png)

(твой компонент)
![2022-09-23-11-14-39](https://user-images.githubusercontent.com/90188872/191950540-88c74f20-59a8-4a32-96aa-8b453d20e7f8.png)

**Comment by vendmm** [comment]
Дропдаун с выбором комнат не работает

https://user-images.githubusercontent.com/90188872/191950737-624703dc-972e-43e4-b3ff-456dbcc1943b.mp4

У этого компонента есть такие же проблемы, как у дропдауна с гостями. Но плейсхолдер лучше написать с большой буквы, чтобы было некое единообразие у компонентов

**Comment by vendmm** [comment]
Чекбоксы меняют свое состояние при клике вне компонента

https://user-images.githubusercontent.com/90188872/191951212-f58c4269-1204-48ab-bd59-413d6cc75034.mp4

**Comment by vendmm** [comment]
В ui-kit показано состояние кнопок при ховере, однако сейчас при наведении ничего не меняется

https://user-images.githubusercontent.com/90188872/191951821-3759a701-105a-434b-be7f-22678ae4c822.mp4

**Comment by vendmm** [comment]
Есть некоторые проблемы с внешним видом тоггла
![2022-09-23-11-19-51](https://user-images.githubusercontent.com/90188872/191952021-a2b8ef48-160f-4504-9974-f4d2eb55a585.png)

**Comment by vendmm** [comment]
Цвет текста в чекбоксах и radio buttons темнее чем на макетах
(макет)
![2022-09-23-14-37-01](https://user-images.githubusercontent.com/90188872/191952277-a07186e6-b1e6-4600-822e-57585926e14c.png)

(твои компоненты)
![2022-09-23-14-38-03](https://user-images.githubusercontent.com/90188872/191952364-da6c5c40-c782-4406-92ce-5db8f467e0c9.png)

И кружок в radio buttons немного смещен от середины

**Comment by vendmm** [comment]
Предустанови пожалуйста даты в календарь, т.к. сейчас форма выглядит странно
![2022-09-23-11-35-59](https://user-images.githubusercontent.com/90188872/191952637-6b361fd1-5cd8-4175-b314-1723fe1855e7.png)

**Comment by vendmm** [comment]
Есть некоторые проблемы с компонентами на мобилках
![2022-09-23-11-29-29](https://user-images.githubusercontent.com/90188872/191952748-9480cbe6-5acb-45e8-a349-4f9a5358dd3d.png)

![2022-09-23-11-31-00](https://user-images.githubusercontent.com/90188872/191952768-338405b7-dfd3-44c3-b4fe-020d146cccca.png)

**Comment by vendmm** [comment]
При открытии меню-бургера не показывается само меню)

https://user-images.githubusercontent.com/90188872/191953011-0f99e35a-d080-4e94-a4db-5794d3ee38f3.mp4

**Comment by CosmoBoyMe** [comment]
> Внешний вид карточки с комнатами не соотв. макетам (макет) ![2022-09-23-11-14-51](https://user-images.githubusercontent.com/90188872/191950496-fd070e03-eb4e-415b-ac85-aae14da4069e.png)
> 
> (твой компонент) ![2022-09-23-11-14-39](https://user-images.githubusercontent.com/90188872/191950540-88c74f20-59a8-4a32-96aa-8b453d20e7f8.png)

проблема только с закругленными краями и с неправильным расположением стрелок да? просто что-то другое я не смог заметить

**Comment by CosmoBoyMe** [comment]
> (твои компоненты) ![2022-09-23-14-38-03](https://user-images.githubusercontent.com/90188872/191952364-da6c5c40-c782-4406-92ce-5db8f467e0c9.png)
> 
> И кружок в radio buttons немного смещен от середины

а какой это браузер? просто я по стилям смотрю вроде должно всё ровно быть( я проверил в chrome и в firefox у меня кружок в середине находится )

**Comment by vendmm** [comment]
> > Внешний вид карточки с комнатами не соотв. макетам (макет) ![2022-09-23-11-14-51](https://user-images.githubusercontent.com/90188872/191950496-fd070e03-eb4e-415b-ac85-aae14da4069e.png)
> > (твой компонент) ![2022-09-23-11-14-39](https://user-images.githubusercontent.com/90188872/191950540-88c74f20-59a8-4a32-96aa-8b453d20e7f8.png)
> 
> проблема только с закругленными краями и с неправильным расположением стрелок да? просто что-то другое я не смог заметить

Да, ты правильно заметил, еще при ховере тень, которая появляется на карточке, отличается от той, что на макете

**Comment by vendmm** [comment]
> > (твои компоненты) ![2022-09-23-14-38-03](https://user-images.githubusercontent.com/90188872/191952364-da6c5c40-c782-4406-92ce-5db8f467e0c9.png)
> > И кружок в radio buttons немного смещен от середины
> 
> а какой это браузер? просто я по стилям смотрю вроде должно всё ровно быть( я проверил в chrome и в firefox у меня кружок в середине находится )

У меня хром, но похоже это проблема масштабирования в Windows. В этом элементе не нужно ничего исправлять)

**Comment by vendmm** [comment]
> Есть некоторые проблемы с компонентами на мобилках
 ![2022-09-23-11-29-29](https://user-images.githubusercontent.com/90188872/191952748-9480cbe6-5acb-45e8-a349-4f9a5358dd3d.png)
> 

Ты внес изменения, но все еще есть проблемы с переносом текста. Сейчас строка с суммой выглядит какой-то оторванной) Мне кажется, будет лучше, если ты ограничишь ширину текста с описанием услуги, и разместишь его и стоимость на одном уровне

![2022-11-03-12-04-41](https://user-images.githubusercontent.com/90188872/199702792-775fab6d-d8d8-4b00-9e71-aa4f23b107c9.png)

**Comment by vendmm** [comment]
При открытии меню хедера контент странно спозиционирован
![2022-11-03-11-58-07](https://user-images.githubusercontent.com/90188872/199704229-c9c07939-765e-40bf-9141-0f509e08f156.png)

**Comment by vendmm** [comment]
При выборе удобств, при кол-ве ванных от 2 до 4 лучше использовать формулировку "ванные комнаты"

![2022-11-03-14-01-28](https://user-images.githubusercontent.com/90188872/199704572-54f4eadf-a3c5-4d80-bf32-0ea10c800a1f.png)

**Comment by vendmm** [comment]
При открытии/закрытии дропдауна немного дергается интерфейс

https://user-images.githubusercontent.com/90188872/199707416-dc9656f7-380c-4958-9839-713a7a5f038b.mp4

**Comment by vendmm** [comment]
На этом компоненте cursor: pointer сохраняется после того, как указатель покидает чекбокс

https://user-images.githubusercontent.com/90188872/199707924-dcb9be43-9406-4128-9507-7f821b31c189.mp4

**Comment by vendmm** [comment]
> Внешний вид карточки с комнатами не соотв. макетам (макет) ![2022-09-23-11-14-51](https://user-images.githubusercontent.com/90188872/191950496-fd070e03-eb4e-415b-ac85-aae14da4069e.png)

Все еще есть проблема с этим компонентом, сейчас он выглядит вот так

https://user-images.githubusercontent.com/90188872/199708378-443a6930-376a-49a4-a75a-f7e1691d567a.mp4

1-тень на стрелочках при ховере должна появляться с обоих сторон + на макетах тень имеет меньший размер
2-при ховере у тени не установлен border-radius

**Comment by vendmm** [comment]
Пропал знак рубля
![2022-11-11-09-59-02](https://user-images.githubusercontent.com/90188872/201282146-5b8d63a6-1c53-4af2-9096-d0f7e28de15c.png)

**Comment by vendmm** [comment]
1. По макетам, на странице colors-types текст с hex-кодом цвета должен иметь жирность
![2022-11-11-10-01-55](https://user-images.githubusercontent.com/90188872/201284879-91c28280-0ae7-4219-97ff-80516ac3b271.png)

2.Лишние закругления снизу на картинке в карточке комнат
![2022-11-11-10-03-42](https://user-images.githubusercontent.com/90188872/201285391-3c3dd11f-0376-48d3-91b7-94700a6a9bb7.png)

3. По макетам, в дропдауне и календаре кнопка "очистить" серого цвета
![2022-11-11-10-10-14](https://user-images.githubusercontent.com/90188872/201285780-1478e420-2398-42a7-93e9-f93652438f74.png)

4. Бордер на кнопке лайка должен быть градиентным
![2022-11-11-10-04-32](https://user-images.githubusercontent.com/90188872/201286043-d78e1665-978a-4058-9ec1-682851c3266f.png)

**Comment by CosmoBoyMe** [comment]
> 1. По макетам, на странице colors-types текст с hex-кодом цвета должен иметь жирность
>    ![2022-11-11-10-01-55](https://user-images.githubusercontent.com/90188872/201284879-91c28280-0ae7-4219-97ff-80516ac3b271.png)
> 
> 2.Лишние закругления снизу на картинке в карточке комнат ![2022-11-11-10-03-42](https://user-images.githubusercontent.com/90188872/201285391-3c3dd11f-0376-48d3-91b7-94700a6a9bb7.png)
> 
> 3. По макетам, в дропдауне и календаре кнопка "очистить" серого цвета
>    ![2022-11-11-10-10-14](https://user-images.githubusercontent.com/90188872/201285780-1478e420-2398-42a7-93e9-f93652438f74.png)
> 4. Бордер на кнопке лайка должен быть градиентным
>    ![2022-11-11-10-04-32](https://user-images.githubusercontent.com/90188872/201286043-d78e1665-978a-4058-9ec1-682851c3266f.png)


3) у меня в макете указано что кнопка отмены должна быть фиолетовой и только при hover должна становиться серой https://ibb.co/wzrDLTK  https://ibb.co/cX4JwFb
4) на макете только фиолетовый цвет указан https://ibb.co/QMnVDBR https://ibb.co/FsMT1gM

**Comment by vendmm** [comment]
> 3. у меня в макете указано что кнопка отмены должна быть фиолетовой и только при hover должна становиться серой https://ibb.co/wzrDLTK  https://ibb.co/cX4JwFb
> 4. на макете только фиолетовый цвет указан https://ibb.co/QMnVDBR https://ibb.co/FsMT1gM

3. Да, ты прав по поводу кнопки на дропдауне/календаре, похоже у меня был старый вариант макетов.
4. Здесь ты тоже прав по поводу бордера. Однако иконка лайка должна, все же, быть градиентной

![2022-11-14-08-45-27](https://user-images.githubusercontent.com/90188872/201584834-6285a8ff-05dc-4e96-89a0-0be313079a05.png)

**Comment by vendmm** [comment]
Нужно добавить нижний отступ на ui-kit, чтобы он соотв. макетам

![2022-11-14-08-50-14](https://user-images.githubusercontent.com/90188872/201585269-55d3e0bd-45ac-4d98-928a-880820e6fa23.png)

**Comment by vendmm** [comment]
> Нужно добавить нижний отступ на ui-kit, чтобы он соотв. макетам
> 
> ![2022-11-14-08-50-14](https://user-images.githubusercontent.com/90188872/201585269-55d3e0bd-45ac-4d98-928a-880820e6fa23.png)

Это не исправлено
