### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by vendmm** [CosmoBoyMe/Toxin#13]
Создай пожалуйста общую страницу, ее можно назвать index, где будут указаны все ссылки на все страницы сайта. Желательно что бы она открывалась при запуске dev режима, т.к. сейчас попадать на другие страницы не очень удобно

**Comment by CosmoBoyMe** [comment]
> Создай пожалуйста общую страницу, ее можно назвать index, где будут указаны все ссылки на все страницы сайта. Желательно что бы она открывалась при запуске dev режима, т.к. сейчас попадать на другие страницы не очень удобно

я почему-то не могу воспроизвести такой баг у себя(хотя он у меня раньше тоже появлялся), надеюсь что теперь он исправился иначе буду думать дальше
