### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by vendmm** [CosmoBoyMe/Toxin#17]
https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/calendar/Calendar.js#L4-L15

https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/calendar/Calendar.js#L22-L24

Я не совсем понимаю, зачем ты сначала объявляешь переменные в конструкторе, потом добавляешь их объект, а затем делаешь подобную деструктуризацию. Такое встречается во многих местах в проекте. Почему сразу не объявить `datePickerElement/fieldElements` и т.д. как переменные класса?

**Comment by CosmoBoyMe** [comment]
> https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/calendar/Calendar.js#L4-L15
> 
> https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/calendar/Calendar.js#L22-L24
> 
> Я не совсем понимаю, зачем ты сначала объявляешь переменные в конструкторе, потом добавляешь их объект, а затем делаешь подобную деструктуризацию. Такое встречается во многих местах в проекте. Почему сразу не объявить `datePickerElement/fieldElements` и т.д. как переменные класса?

Просто для структуры, как например вот здесь https://github.com/CosmoBoyMe/Toxin/blob/0cf76603be52d3a7a0f428e0e48bc48038000bab/src/components/range-slider/RangeSlider.js#L12-L20

**Comment by vendmm** [comment]
> 
> Просто для структуры, как например вот здесь
> 
> https://github.com/CosmoBoyMe/Toxin/blob/0cf76603be52d3a7a0f428e0e48bc48038000bab/src/components/range-slider/RangeSlider.js#L12-L20

По моему мнению, такой подход излишен. По сути, из-за  деструктуризации в методах у тебя везде добавляется +1 строка. К тому же, в объемных методах не совсем понятно, переменная относится к классу или она было объявлена внутри метода, из-за чего приходится скролить в начало.

**Comment by vendmm** [comment]
> > Просто для структуры, как например вот здесь
> > https://github.com/CosmoBoyMe/Toxin/blob/0cf76603be52d3a7a0f428e0e48bc48038000bab/src/components/range-slider/RangeSlider.js#L12-L20
> 
> По моему мнению, такой подход излишен. По сути, из-за деструктуризации в методах у тебя везде добавляется +1 строка. К тому же, в объемных методах не совсем понятно, переменная относится к классу или она было объявлена внутри метода, из-за чего приходится скролить в начало.


К тому же в проекте отсутствует какой-то единый стиль использования этой деструктуризации, где-то она есть, а где-то нет.
https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/calendar/Calendar.js#L83

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/rate/Rate.js#L16

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/calendar/Calendar.js#L94-L96

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/like-button/LikeButton.js#L9-L10

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/room-dropdown/RoomDropdown.js#L11

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/guest-dropdown/GuestDropdown.js#L25

**Comment by vendmm** [comment]
В этом классе происходит поиск элементов, которые расположены в другом миксине. Если кто-нибудь изменит имя этих классов, то компонент будет сломан или же придется менять именование в двух местах. Это не очень удобно, поэтому лучше сделать компонент amount-select частью дропдауна

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/components/dropdown/Dropdown.js#L9-L11
