### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by RamilNazmiev** [CosmoBoyMe/Toxin#5]
- Минусовых отступов  быть  не должно 
![image](https://user-images.githubusercontent.com/94169565/172180771-fb64623f-09bc-4518-a11f-de50b02e1f74.png)

**Comment by RamilNazmiev** [comment]
- вроде так нечего не ломается , если все норм то убери лишнею обертку , 
![image](https://user-images.githubusercontent.com/94169565/172868800-8b91a043-5790-496c-be64-6558f6bd685d.png)

**Comment by RamilNazmiev** [comment]
У тебя в header  , прописан background-color: #fff; он у тебя по умолчанию идет , надо во всем проекте пройтись и найди свойства по умолчанию и удалить 
![image](https://user-images.githubusercontent.com/94169565/172870789-4863fb64-8920-40f9-ae99-e5ad63f47fef.png)

**Comment by RamilNazmiev** [comment]
Почему по середине  а не первой строчкой ?
![image](https://user-images.githubusercontent.com/94169565/172873278-309034a4-0f7c-4ba2-a594-dc27ba79dce2.png)

**Comment by CosmoBoyMe** [comment]
> * вроде так нечего не ломается , если все норм то убери лишнею обертку ,
>   ![image](https://user-images.githubusercontent.com/94169565/172868800-8b91a043-5790-496c-be64-6558f6bd685d.png)

Если убрать обёртку то у нижнего footer пропадёт нижняя черта на всю длину, она станет на длину контейнера

**Comment by CosmoBoyMe** [comment]
> Почему по середине а не первой строчкой ? ![image](https://user-images.githubusercontent.com/94169565/172873278-309034a4-0f7c-4ba2-a594-dc27ba79dce2.png)

так обрабатывает css stylelint, если надо могу изменить настройки, просто не где не было указано как должен быть оформлен css код, поэтому взял самый популярный config и добавил его в свой проект

**Comment by RamilNazmiev** [comment]
> > * вроде так нечего не ломается , если все норм то убери лишнею обертку ,
> >   ![image](https://user-images.githubusercontent.com/94169565/172868800-8b91a043-5790-496c-be64-6558f6bd685d.png)
> 
> Если убрать обёртку то у нижнего footer пропадёт нижняя черта на всю длину, она станет на длину контейнера

Принято

**Comment by RamilNazmiev** [comment]
> > Почему по середине а не первой строчкой ? ![image](https://user-images.githubusercontent.com/94169565/172873278-309034a4-0f7c-4ba2-a594-dc27ba79dce2.png)
> 
> так обрабатывает css stylelint, если надо могу изменить настройки, просто не где не было указано как должен быть оформлен css код, поэтому взял самый популярный config и добавил его в свой проект

Попробуй настроит, если что это не крично.

**Comment by CosmoBoyMe** [comment]
> У тебя в header , прописан background-color: #fff; он у тебя по умолчанию идет , надо во всем проекте пройтись и найди свойства по умолчанию и удалить ![image](https://user-images.githubusercontent.com/94169565/172870789-4863fb64-8920-40f9-ae99-e5ad63f47fef.png)

background-color 
для footer и header установлен, потому что на странице headersAndFooters установлен серый фон, для компонентов форм он установлен, потому что они находятся на фоне с изображением
![form](https://user-images.githubusercontent.com/52293247/172998424-91287265-a167-4bf4-8315-8072787ea35c.PNG)
![footer](https://user-images.githubusercontent.com/52293247/172998459-974d9bc6-38e8-4642-8a84-9e4c7776ccc8.PNG)
