### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by vendmm** [CosmoBoyMe/Toxin#8]
Странный комментарий в компоненте)

https://github.com/CosmoBoyMe/Toxin/blob/3be78d6d76a76ff09a5656925d55c417b8352880/src/components/amount-select/amount-select.pug#L18

**Comment by vendmm** [comment]
В некоторых компонентах для именования модификаторов "ключ-значение" ты используешь применяемые стили, это некорректно и лучше придерживаться более обобщенных имен. Так же, тернарный оператор можно упростить таким образом - `calendar__date-picker_position_absolute`

https://github.com/CosmoBoyMe/Toxin/blob/3be78d6d76a76ff09a5656925d55c417b8352880/src/components/calendar/calendar.pug#L19

**Comment by vendmm** [comment]
Это два отдельных миксина, не совсем понятно, почему они находятся в одной папке?

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/ui-kit/color-item/color-item.pug#L1

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/ui-kit/color-type-item/color-type-item.pug#L1

**Comment by vendmm** [comment]
в миксинах не для всех аргументов указаны дефолтные параметры

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/subscription-field/subscription-field.pug#L1

**Comment by vendmm** [comment]
В этих случаях неверно используется булевый модификатор, т.к. 
1 - названия модификаторов не соотв. правилам именования
2 - тут более логично применить модификатор "ключ-значение", т.к. в целом важно значение результата сравнения, от которого зависит тип применяемых стилей

Более подробно о типах модификаторов можно почитать [тут](https://ru.bem.info/methodology/quick-start/#%D1%82%D0%B8%D0%BF%D1%8B-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2)

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/rate/rate.pug#L6

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/bullet-list/bullet-list.pug#L3-L6

**Comment by vendmm** [comment]
Ты используешь модификатор `_visually_hidden` для обозначения скрытых инпутов. Меня смущает его название и, в целом, мотивы использования:
1- имя модификатора перекликается с названием стилей, которые могут быть применены к компоненту и логичнее было бы оставить булевый модификатор hidden
2- не совсем понятно зачем ты вообще используешь модификатор, но при этом не указываешь никаких стилей для элемента `.checkbox-item__input`

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/checkbox-item/checkbox-item.pug#L4-L7

**Comment by vendmm** [comment]
Имена компонентов, модификаторов и аргументов лучше указывать полностью, без сокращений

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/submit-btn/submit-btn.pug#L1

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/amount-select/amount-select.pug#L5-L7

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/dropdown/Dropdown.js#L8-L13

**Comment by vendmm** [comment]
> В некоторых компонентах для именования модификаторов "ключ-значение" ты используешь применяемые стили, это некорректно и лучше придерживаться более обобщенных имен. Так же, тернарный оператор можно упростить таким образом - `calendar__date-picker_position_absolute`
> 
> https://github.com/CosmoBoyMe/Toxin/blob/3be78d6d76a76ff09a5656925d55c417b8352880/src/components/calendar/calendar.pug#L19

Здесь я была невнимательна) Тернарные операторы можно упростить с помощью  &&, вот так: 

`class= type && "calendar__date-picker_closed calendar__date-picker_shift_top"`

https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/calendar/calendar.pug#L18

**Comment by CosmoBoyMe** [comment]
> Это два отдельных миксина, не совсем понятно, почему они находятся в одной папке?
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/ui-kit/color-item/color-item.pug#L1
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/ui-kit/color-type-item/color-type-item.pug#L1

Эти миксины используются только для страницы colors-and-types, мне кажется логичнее их было бы оставить в одной папке что бы они не мешались среди "нормальных" миксинов, просто я сомневаюсь что они ещё где-то будут когда-то использоваться кроме как для страницы с цветами

**Comment by CosmoBoyMe** [comment]
> В этих случаях неверно используется булевый модификатор, т.к.
> 1 - названия модификаторов не соотв. правилам именования



> В этих случаях неверно используется булевый модификатор, т.к. 1 - названия модификаторов не соотв. правилам именования 2 - тут более логично применить модификатор "ключ-значение", т.к. в целом важно значение результата сравнения, от которого зависит тип применяемых стилей
> 
> Более подробно о типах модификаторов можно почитать [тут](https://ru.bem.info/methodology/quick-start/#%D1%82%D0%B8%D0%BF%D1%8B-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2)
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/rate/rate.pug#L6
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/bullet-list/bullet-list.pug#L3-L6

1) если я правильно понял замечание, то тут имеется в виду не правильно написан модификатор для иконки, но тут нету не какого модификатора тут есть только название иконки(текст обычный) который может по факту быть любым                      
2) не совсем понятно что здесь не так, у меня вроде как модификатор title_h3 используется 'ключ-значение'

**Comment by CosmoBoyMe** [comment]
> Имена компонентов, модификаторов и аргументов лучше указывать полностью, без сокращений
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/submit-btn/submit-btn.pug#L1
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/amount-select/amount-select.pug#L5-L7
> 
> https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/dropdown/Dropdown.js#L8-L13

А разве часто используемые сокращения тоже нужно писать полностью? Вместо btn нужно писать button ? css классы как я понимаю тоже нужно писать полностью?

**Comment by vendmm** [comment]
> 
> 1. если я правильно понял замечание, то тут имеется в виду не правильно написан модификатор для иконки, но тут нету не какого модификатора тут есть только название иконки(текст обычный) который может по факту быть любым
> 2. не совсем понятно что здесь не так, у меня вроде как модификатор title_h3 используется 'ключ-значение'


1- да, ты прав, извини за мою невнимательность)
2- модификатор "ключ-значение" имеет вид `имя-блока_имя-модификатора_значение-модификатора` или `имя-блока__имя-элемента_имя-модификатора_значение-модификатора`. У тебя `bullet-list__title_h3`, где:
bullet-list - имя блока
title - имя элемента
h3 - имя модификатора
Такая структура именования , которая у тебя сейчас, подходит для [булевых](https://ru.bem.info/methodology/quick-start/#%D0%B1%D1%83%D0%BB%D0%B5%D0%B2%D1%8B%D0%B9) модификаторов

**Comment by vendmm** [comment]
> 
> А разве часто используемые сокращения тоже нужно писать полностью? Вместо btn нужно писать button ? css классы как я понимаю тоже нужно писать полностью?
>

Есть общепринятые сокращения, например min, max, img. В случае с btn и El я не уверена, т.к. для некоторых людей такое именование может быть не совсем очевидно, по этой причине, лучше писать полные названия для компонентов, классов, переменных и т.д.

**Comment by vendmm** [comment]
> > Это два отдельных миксина, не совсем понятно, почему они находятся в одной папке?
> > https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/ui-kit/color-item/color-item.pug#L1
> > 
> > https://github.com/CosmoBoyMe/Toxin/blob/8da06011a5479e53304cb301eb0e67df9271606d/src/components/ui-kit/color-type-item/color-type-item.pug#L1
> 
> Эти миксины используются только для страницы colors-and-types, мне кажется логичнее их было бы оставить в одной папке что бы они не мешались среди "нормальных" миксинов, просто я сомневаюсь что они ещё где-то будут когда-то использоваться кроме как для страницы с цветами

Я не думаю что две папки внутри components могут как-то помешать восприятию проекта, просто сейчас эта вложенность кажется не обоснованной, даже с учетом твоих аргументов)

**Comment by vendmm** [comment]
Зачем здесь в миксин календаря передается класс? Далее он нигде не используется, а если и должен был использоваться, то получится БЭМ микс. В стандартах([тут](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.5) и [тут](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.6)) не рекомендуется их создавать
https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/search-rooms-form/search-rooms-form.pug#L9

**Comment by vendmm** [comment]
Зачем ты два раза деструктуризируешь одни и те же аргументы?
https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/header/header.pug#L4-L5

**Comment by vendmm** [comment]
https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/color-type-item/color-type-item.pug#L1

Мне кажется для миксина, который показывает различные варианты текстов, здесь выбрано не совсем хорошее название

**Comment by OlgaMaurer** [comment]
Компонент с диаграммой, который используется на странице поиска номеров, включает в себя и лейблы с обозначениями определенных цветов на диаграмме. Сейчас эти лейблы являются элементами страницы 

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/pages/web/room-details/room-details.pug#L51-L55

**Comment by vendmm** [comment]
Здесь неверно выбран тип модификаторов, я уже указывала на эту проблему ранее, пожалуйста проверь все компоненты еще раз

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/pages/web/room-details/room-details.pug#L52-L55

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/pages/ui-kit/form-elements/form-elements.pug#L53

**Comment by vendmm** [comment]
> https://github.com/CosmoBoyMe/Toxin/blob/03a732b5aeb93782b985fe3c929fc2cb6de7f856/src/components/color-type-item/color-type-item.pug#L1
> 
> Мне кажется для миксина, который показывает различные варианты текстов, здесь выбрано не совсем хорошее название

В этом ишью я говорила о том, что стоит изменить имя самого миксина, например, назвать его text-type. Такое название более корректно описывает компонент

**Comment by vendmm** [comment]
На странице form-elements встречаются классы с префиксом js, которые нигде не используются

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/pages/ui-kit/form-elements/form-elements.pug#L42

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/pages/ui-kit/form-elements/form-elements.pug#L44
