### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by vendmm** [CosmoBoyMe/Toxin#9]
Данные в форме бронирования не должны быть захардкожены, они должны вычисляться на основе суточной стоимости номера, кол-ва дней и скидок.

https://github.com/CosmoBoyMe/Toxin/blob/3be78d6d76a76ff09a5656925d55c417b8352880/src/components/booking-form/booking-form.pug#L17-L18

**Comment by vendmm** [comment]
Мне кажется, что bullet-list излишне декомпозирован и будет лучше, если ты совместишь bullet-item и bullet-list в один компонент

**Comment by vendmm** [comment]
Компоненты checkbox-item и rich-checkbox-item практически идентичны, их стоит объединить в один

**Comment by vendmm** [comment]
Мне кажется стоит упростить все компоненты инпутов, где можно указать id. Вообще использование этого атрибута не рекомендуется [стандартами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.8) (там конечно есть исключения, но они не подходят, в твоем случае). 
Компонент masked-field, к примеру, можно упростить вот так:
![2022-10-26-12-02-05](https://user-images.githubusercontent.com/90188872/198260639-9a62e1ec-e3f7-40b7-8af7-4351f6bdcaaa.png)

**Comment by vendmm** [comment]
Компонент с диаграммой, который используется на странице поиска номеров, включает в себя и лейблы с обозначениями определенных цветов на диаграмме. Сейчас эти лейблы являются элементами страницы 

https://github.com/CosmoBoyMe/Toxin/blob/6823d4bf10c2e257e741eb8b330a782ec718671b/src/pages/web/room-details/room-details.pug#L51-L55

**Comment by vendmm** [comment]
При создании элементов компонента пагинации указываются классы с префиксом js-, они же используются для стилизации. Стоит разделять классы для стилей и для работы в js файлах

https://github.com/CosmoBoyMe/Toxin/blob/b17378efabb98c029ddf14ac3b827e2dede6ed63/src/components/pagination/Pagination.js#L21-L24

https://github.com/CosmoBoyMe/Toxin/blob/b17378efabb98c029ddf14ac3b827e2dede6ed63/src/components/pagination/pagination.scss#L18-L19

**Comment by vendmm** [comment]
Здесь лучше использовать булевый модификатор

https://github.com/CosmoBoyMe/Toxin/blob/b17378efabb98c029ddf14ac3b827e2dede6ed63/src/components/header/Header.js#L10

**Comment by CosmoBoyMe** [comment]
> Здесь лучше использовать булевый модификатор
> 
> https://github.com/CosmoBoyMe/Toxin/blob/b17378efabb98c029ddf14ac3b827e2dede6ed63/src/components/header/Header.js#L10

а будет вообще тогда ясно что именно отключено ? просто если бы была кнопка то тогда понятно, а тут body element и мне показалось что будет не совсем понятно для чего данный модификатор

**Comment by vendmm** [comment]
> > Здесь лучше использовать булевый модификатор
> > https://github.com/CosmoBoyMe/Toxin/blob/b17378efabb98c029ddf14ac3b827e2dede6ed63/src/components/header/Header.js#L10
> 
> а будет вообще тогда ясно что именно отключено ? просто если бы была кнопка то тогда понятно, а тут body element и мне показалось что будет не совсем понятно для чего данный модификатор

Здесь можно использовать `adjectival phrase`, такой пример есть в [стандартах](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.1), т.е. получится body_with-disabled-scroll

upd. Хотя, в целом, в этом кейсе можно и не использовать дизейбл скрола для body, т.к. хедер занимает все пространство экрана и пользователь не будет видеть, что страница сколится
